### ISSUE TITLE
Both VBAN_Recv and VBAN_Send return an error

### ISSUE THREAD

**Issue by giulianobernardi** [TheStaticTurtle/pyVBAN#2] opened 2021-02-17 08:45 UTC
Hi, I was playing around with this and I found the following problems:

- When I run `VBAN_Recv()`, it yields the following error: `struct.error: unpack requires a buffer of 8 bytes` on the line `self.stream_frameCounter = struct.unpack("l",data[24:28])[0]`. I just tried to replace the line with `self.stream_frameCounter = struct.unpack("l",data[24:32])[0]` and it works fine. Not sure why this 8 bytes constraint was not the case on your system...

- When I run `VBAN_Send()`, it keeps yielding the following error `[Errno 56] Socket is already connected`. I tried to change the `PORT` number, assuming socket refers to that, without success.

Any idea of why that might be?

**Comment by giulianobernardi** [comment] 2021-02-17 09:21
I found out [this discussion](https://github.com/zerovm/zerocloud/pull/87) where they mention it might be due to the usage of `sendto` which gives some headaches when running python on macOS (which I'm using).

If I replace `sendto` with `send`, the error vanishes, but now I got something else :D 

`an integer is required (got type tuple)`

**Comment by TheStaticTurtle** [comment] 2021-02-17 12:59
All these socket issues seems to be OSX related (see https://trac.clozure.com/ccl/ticket/1252), apparently calling `sock.connect` and after that calling `sock.sendto` with a destination causes an error. Please comment line 93 (`self.sock.connect((self.toIp,self.toPort))`) and try the send again. (It might still not work due to the next issue)

As receive and for the `struct.unpack`, please keep the original array ([24:28]) the protocol specification calls for a 32bit unsigned integer (eg 4byte). Could you tell me which platform you are running? (arm/arm64/x86)
For testing could you replace line 54 by this: 
```py
frame_counter_bytes=data[24:28]
self.stream_frameCounter = (frame_counter_bytes[0]) + (frame_counter_bytes[1]<<8) + (frame_counter_bytes[2]<<16) + (frame_counter_bytes[3]<<24)
```
This should make the receive part work.

**Comment by giulianobernardi** [comment] 2021-02-17 17:43
Hi @TheStaticTurtle 
Thanks for your help.

Let's start from the **receive part**. I replaced the code you posted and it works fine! 
I'm running a machine with a [Quad-Core Intel Core i7](https://ark.intel.com/content/www/us/en/ark/products/137979/intel-core-i7-8559u-processor-8m-cache-up-to-4-50-ghz.html), so the instruction set should be Intel 64 (or is it x86-64?!?).

Regarding the **send part**, commenting out the line you mentioned does indeed silence the error and allows to send data to another machine (a Win10 machine running VoiceMeeter). However, when listening to the signal on the receiving side, I can hear some kind of crackling noise (such a crackling noise is not present in the signal sent by the Win10 machine and received on my MacBook using `VBAN_Recv`). Is this anything you've run into before?

**Comment by TheStaticTurtle** [comment] 2021-02-17 18:17
Ok, could you retry the receive part with `self.stream_frameCounter = struct.unpack("<L",data[24:28])[0]`

As for the crackling I'm 99% sure it is caused by the fact that `struct.pack` is generating 8bytes instead of 4bytes on your platform, could you try to replace this line `header += struct.pack("l",self.framecounter)` by `header += struct.pack("<L",self.framecounter)` and if it's still not working with: 
```py
header += bytes([(self.framecounter & 0x000000ff) >>0 ])
header += bytes([(self.framecounter & 0x0000ff00) >>8 ])
header += bytes([(self.framecounter & 0x00ff0000) >>16])
header += bytes([(self.framecounter & 0xff000000) >>24])
```

**Comment by giulianobernardi** [comment] 2021-02-17 21:14
**Receive**: Using `self.stream_frameCounter = struct.unpack("<L",data[24:28])[0]` works fine (as did your previous suggestion).

**Send**: Both your suggestions work fine and take complete care of the crackling problem! :)

Thanks again for the help! I still need to run a few more tests cause when I run `VBAN_Recv` I get a larger latency (at least perceptually, I did not measure it) compared with what I get with `VBAN_Send`, but I assume that might be related to the specific setup I'm using.

**Comment by TheStaticTurtle** [comment] 2021-02-17 21:37
Ok I pushed the changes to master please test them and if it works at excepted, I'll close the issue.
As for the latency I know that it's more than voicemeeter to voicemeeter, probably python or pyaudio adding the latency

**Comment by giulianobernardi** [comment] 2021-02-17 21:40
Cool! I'll play a bit more with it in the coming days and let you know if I spot any other problems related to this issue.
Cheers.

**Closed as completed** 2024-03-04 22:39 UTC
